apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-shared-namespaces
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  path: ./clusters/hlcl1/infra/shared-namespaces/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
