---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nas-ssh-secret
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: nas-ssh-secret
    creationPolicy: Owner
  data:
    - secretKey: ssh_private_key # pragma: allowlist secret
      remoteRef:
        key: arc/nas-deploy-key
        property: ssh_private_key
    - secretKey: known_hosts # pragma: allowlist secret
      remoteRef:
        key: arc/nas-deploy-key
        property: known_hosts
    - secretKey: nas_host # pragma: allowlist secret
      remoteRef:
        key: arc/nas-deploy-key
        property: nas_host
    - secretKey: nas_user # pragma: allowlist secret
      remoteRef:
        key: arc/nas-deploy-key
        property: nas_user
