---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sops-age-secret
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: sops-age-secret
    creationPolicy: Owner
  data:
    - secretKey: private_key # pragma: allowlist secret
      remoteRef:
        key: arc/sops-age-key
        property: private_key
