apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cloudnativepg
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  path: ./clusters/hlcl1/infra/databases/cloudnativepg/chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
