apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ff-app-secret
  namespace: ff-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: ff-app-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret # pragma: allowlist secret
      remoteRef:
        key: ff/app
        property: jwt-secret
