apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ff-production
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ff
  filterTags:
    pattern: '^main-[0-9]{14}$'
  policy:
    alphabetical:
      order: asc
