apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: ">=2.26.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: pihole-secret
      valuesKey: adminPassword
      targetPath: adminPassword
  values:
    replicaCount: 1
    image:
      tag: "latest"
    DNS1: ""
    DNS2: ""
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: 192.168.0.245
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole
    serviceWeb:
      type: LoadBalancer
      loadBalancerIP: 192.168.0.245
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole
    persistentVolumeClaim:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteOnce
      size: 2Gi
    podAntiAffinity:
      enabled: true
    extraEnvVars:
      TZ: "America/New_York"
      FTLCONF_webserver_port: "80"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
